let trainingDataS = [
  {
    deck: [
      { card: 9, type: 3 },
      { card: 1, type: 3 },
      { card: 8, type: 4 },
      { card: 8, type: 2 },
      { card: 10, type: 4 },
      { card: 9, type: 2 },
      { card: 9, type: 1 },
      { card: 4, type: 4 },
      { card: 5, type: 2 },
      { card: 8, type: 1 },
      { card: 7, type: 2 },
      { card: 2, type: 4 },
      { card: 10, type: 4 },
      { card: 6, type: 4 },
      { card: 11, type: 1 },
      { card: 11, type: 2 },
      { card: 10, type: 1 },
      { card: 4, type: 1 },
      { card: 11, type: 3 },
      { card: 12, type: 2 },
      { card: 13, type: 3 },
      { card: 7, type: 3 },
      { card: 13, type: 2 },
      { card: 2, type: 4 },
    ],
    stacks: [
      [{ card: 10, type: 2 }],
      [
        { card: 3, type: 4 },
        { card: 7, type: 4 },
      ],
      [
        { card: 3, type: 1 },
        { card: 4, type: 3 },
        { card: 2, type: 2 },
      ],
      [
        { card: 2, type: 1 },
        { card: 3, type: 3 },
        { card: 11, type: 4 },
        { card: 8, type: 3 },
      ],
      [
        { card: 5, type: 3 },
        { card: 4, type: 2 },
        { card: 3, type: 2 },
        { card: 1, type: 4 },
        { card: 9, type: 4 },
      ],
      [
        { card: 6, type: 2 },
        { card: 6, type: 1 },
        { card: 12, type: 1 },
        { card: 12, type: 3 },
        { card: 5, type: 4 },
        { card: 1, type: 1 },
      ],
      [
        { card: 12, type: 4 },
        { card: 1, type: 2 },
        { card: 7, type: 1 },
        { card: 13, type: 1 },
        { card: 5, type: 1 },
        { card: 13, type: 4 },
        { card: 6, type: 3 },
      ],
    ],
  },
  {
    deck: [
      { card: 10, type: 1 },
      { card: 13, type: 2 },
      { card: 13, type: 3 },
      { card: 8, type: 3 },
      { card: 4, type: 4 },
      { card: 10, type: 4 },
      { card: 8, type: 4 },
      { card: 6, type: 4 },
      { card: 6, type: 2 },
      { card: 4, type: 3 },
      { card: 11, type: 2 },
      { card: 13, type: 1 },
      { card: 12, type: 3 },
      { card: 12, type: 1 },
      { card: 7, type: 4 },
      { card: 1, type: 2 },
      { card: 9, type: 2 },
      { card: 3, type: 1 },
      { card: 10, type: 3 },
      { card: 10, type: 2 },
      { card: 12, type: 2 },
      { card: 5, type: 1 },
      { card: 5, type: 4 },
      { card: 9, type: 1 },
    ],
    stacks: [
      [{ card: 13, type: 4 }],
      [
        { card: 1, type: 3 },
        { card: 2, type: 3 },
      ],
      [
        { card: 2, type: 1 },
        { card: 4, type: 1 },
        { card: 8, type: 1 },
      ],
      [
        { card: 6, type: 1 },
        { card: 2, type: 4 },
        { card: 9, type: 4 },
        { card: 8, type: 2 },
      ],
      [
        { card: 1, type: 4 },
        { card: 5, type: 3 },
        { card: 11, type: 3 },
        { card: 3, type: 3 },
        { card: 7, type: 3 },
      ],
      [
        { card: 7, type: 2 },
        { card: 3, type: 2 },
        { card: 7, type: 1 },
        { card: 9, type: 3 },
        { card: 6, type: 3 },
        { card: 11, type: 4 },
      ],
      [
        { card: 11, type: 1 },
        { card: 12, type: 4 },
        { card: 4, type: 2 },
        { card: 1, type: 1 },
        { card: 2, type: 3 },
        { card: 3, type: 4 },
        { card: 5, type: 2 },
      ],
    ],
  },
  {
    deck: [
      { card: 10, type: 4 },
      { card: 4, type: 4 },
      { card: 13, type: 1 },
      { card: 13, type: 4 },
      { card: 13, type: 3 },
      { card: 5, type: 3 },
      { card: 3, type: 2 },
      { card: 5, type: 1 },
      { card: 10, type: 3 },
      { card: 12, type: 2 },
      { card: 2, type: 4 },
      { card: 4, type: 1 },
      { card: 6, type: 1 },
      { card: 7, type: 1 },
      { card: 2, type: 1 },
      { card: 6, type: 4 },
      { card: 1, type: 3 },
      { card: 7, type: 3 },
      { card: 11, type: 1 },
      { card: 13, type: 2 },
      { card: 7, type: 4 },
      { card: 11, type: 2 },
      { card: 1, type: 2 },
      { card: 8, type: 1 },
    ],
    stacks: [
      [{ card: 1, type: 1 }],
      [
        { card: 2, type: 2 },
        { card: 10, type: 2 },
      ],
      [
        { card: 9, type: 2 },
        { card: 9, type: 4 },
        { card: 12, type: 3 },
      ],
      [
        { card: 6, type: 3 },
        { card: 5, type: 2 },
        { card: 8, type: 3 },
        { card: 3, type: 1 },
      ],
      [
        { card: 4, type: 2 },
        { card: 10, type: 1 },
        { card: 12, type: 4 },
        { card: 12, type: 1 },
        { card: 1, type: 4 },
      ],
      [
        { card: 7, type: 2 },
        { card: 6, type: 2 },
        { card: 8, type: 2 },
        { card: 9, type: 3 },
        { card: 11, type: 4 },
        { card: 8, type: 4 },
      ],
      [
        { card: 3, type: 3 },
        { card: 4, type: 3 },
        { card: 11, type: 3 },
        { card: 2, type: 3 },
        { card: 9, type: 1 },
        { card: 5, type: 4 },
        { card: 3, type: 4 },
      ],
    ],
  },
  {
    deck: [
      { card: 8, type: 3 },
      { card: 9, type: 1 },
      { card: 9, type: 2 },
      { card: 2, type: 1 },
      { card: 3, type: 2 },
      { card: 5, type: 4 },
      { card: 11, type: 2 },
      { card: 2, type: 2 },
      { card: 6, type: 2 },
      { card: 12, type: 4 },
      { card: 9, type: 3 },
      { card: 10, type: 1 },
      { card: 8, type: 4 },
      { card: 5, type: 2 },
      { card: 12, type: 2 },
      { card: 12, type: 3 },
      { card: 10, type: 4 },
      { card: 4, type: 1 },
      { card: 1, type: 1 },
      { card: 1, type: 3 },
      { card: 2, type: 4 },
      { card: 13, type: 3 },
      { card: 2, type: 3 },
      { card: 12, type: 1 },
    ],
    stacks: [
      [{ card: 6, type: 1 }],
      [
        { card: 1, type: 2 },
        { card: 13, type: 2 },
      ],
      [
        { card: 4, type: 2 },
        { card: 4, type: 4 },
        { card: 8, type: 2 },
      ],
      [
        { card: 6, type: 4 },
        { card: 13, type: 1 },
        { card: 10, type: 2 },
        { card: 7, type: 1 },
      ],
      [
        { card: 10, type: 3 },
        { card: 11, type: 4 },
        { card: 7, type: 2 },
        { card: 3, type: 4 },
        { card: 7, type: 4 },
      ],
      [
        { card: 11, type: 3 },
        { card: 11, type: 1 },
        { card: 5, type: 1 },
        { card: 6, type: 3 },
        { card: 8, type: 1 },
        { card: 1, type: 4 },
      ],
      [
        { card: 5, type: 3 },
        { card: 9, type: 4 },
        { card: 3, type: 1 },
        { card: 4, type: 3 },
        { card: 7, type: 3 },
        { card: 13, type: 4 },
        { card: 3, type: 3 },
      ],
    ],
  },
  {
    deck: [
      { card: 13, type: 3 },
      { card: 2, type: 4 },
      { card: 12, type: 3 },
      { card: 7, type: 2 },
      { card: 7, type: 3 },
      { card: 9, type: 1 },
      { card: 9, type: 2 },
      { card: 8, type: 3 },
      { card: 11, type: 3 },
      { card: 3, type: 2 },
      { card: 4, type: 2 },
      { card: 9, type: 4 },
      { card: 7, type: 4 },
      { card: 3, type: 3 },
      { card: 1, type: 3 },
      { card: 10, type: 1 },
      { card: 12, type: 1 },
      { card: 13, type: 4 },
      { card: 6, type: 1 },
      { card: 8, type: 4 },
      { card: 12, type: 4 },
      { card: 10, type: 2 },
      { card: 2, type: 3 },
      { card: 5, type: 2 },
    ],
    stacks: [
      [{ card: 3, type: 4 }],
      [
        { card: 13, type: 2 },
        { card: 5, type: 4 },
      ],
      [
        { card: 6, type: 2 },
        { card: 1, type: 1 },
        { card: 1, type: 2 },
      ],
      [
        { card: 5, type: 3 },
        { card: 5, type: 1 },
        { card: 4, type: 4 },
        { card: 13, type: 1 },
      ],
      [
        { card: 11, type: 2 },
        { card: 4, type: 3 },
        { card: 6, type: 3 },
        { card: 10, type: 4 },
        { card: 11, type: 4 },
      ],
      [
        { card: 7, type: 1 },
        { card: 10, type: 3 },
        { card: 11, type: 1 },
        { card: 8, type: 2 },
        { card: 1, type: 4 },
        { card: 4, type: 1 },
      ],
      [
        { card: 2, type: 1 },
        { card: 6, type: 4 },
        { card: 9, type: 3 },
        { card: 8, type: 1 },
        { card: 2, type: 2 },
        { card: 3, type: 1 },
        { card: 12, type: 2 },
      ],
    ],
  },
  {
    deck: [
      { card: 11, type: 1 },
      { card: 4, type: 2 },
      { card: 12, type: 4 },
      { card: 6, type: 3 },
      { card: 3, type: 2 },
      { card: 13, type: 1 },
      { card: 7, type: 3 },
      { card: 4, type: 1 },
      { card: 6, type: 4 },
      { card: 2, type: 1 },
      { card: 4, type: 3 },
      { card: 2, type: 3 },
      { card: 9, type: 3 },
      { card: 1, type: 3 },
      { card: 3, type: 1 },
      { card: 8, type: 2 },
      { card: 13, type: 4 },
      { card: 10, type: 1 },
      { card: 4, type: 4 },
      { card: 2, type: 2 },
      { card: 3, type: 4 },
      { card: 8, type: 3 },
      { card: 3, type: 3 },
      { card: 5, type: 2 },
    ],
    stacks: [
      [{ card: 9, type: 1 }],
      [
        { card: 6, type: 2 },
        { card: 10, type: 4 },
      ],
      [
        { card: 4, type: 2 },
        { card: 8, type: 4 },
        { card: 10, type: 2 },
      ],
      [
        { card: 12, type: 1 },
        { card: 13, type: 3 },
        { card: 13, type: 2 },
        { card: 10, type: 3 },
      ],
      [
        { card: 1, type: 4 },
        { card: 5, type: 4 },
        { card: 8, type: 1 },
        { card: 5, type: 3 },
        { card: 11, type: 3 },
      ],
      [
        { card: 5, type: 1 },
        { card: 7, type: 4 },
        { card: 2, type: 4 },
        { card: 9, type: 4 },
        { card: 12, type: 2 },
        { card: 7, type: 1 },
      ],
      [
        { card: 12, type: 3 },
        { card: 1, type: 1 },
        { card: 11, type: 4 },
        { card: 6, type: 1 },
        { card: 7, type: 2 },
        { card: 11, type: 2 },
        { card: 1, type: 2 },
      ],
    ],
  },
];

module.exports = { trainingDataS };
